version: "3.1"

services:
  db:
    image: mysql:latest
    container_name: mysql-terrarossa
    ports:
      - 3306:3306
    # User/password for local dev: root/password, if not overwritten by command line option when starting the container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: terrarossa
