name: Cypress Parallel Tests
run-name: branch {${{ github.head_ref || github.ref_name }}} commit {${{ github.event.head_commit.message || 'pull request'}}}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEBUG: "cypress:server:args"
  DATABASE_URL: ${{vars.DATABASE_URL}}
  NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL: ${{vars.NEXTAUTH_URL}}
  AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
  AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
  AUTH0_ISSUER: ${{vars.AUTH0_ISSUER}}
  AUTH_BASE_URL: ${{vars.AUTH_BASE_URL}}
  CYPRESS_AUTH0_USER: ${{secrets.CYPRESS_AUTH0_USER}}
  CYPRESS_AUTH0_PW: ${{secrets.CYPRESS_AUTH0_PW}}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
      options: --user 1001 #needed?

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          runTests: false

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: .next

  ui-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: terrarossa
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    container:
      image: cypress/browsers:latest
      options: --user 1001 #needed?
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .next

      - name: Cypress info
        run: npx cypress info

      - name: Node info
        run: node -v

      - name: __e Dir
        run: ls /__e

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome"
          spec: cypress/tests/ui/*
          config-file: cypress.config.ts
