# keep name short as it is displayed in readme badge
name: Cypress CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
env:
  NODE_ENV: "test" # to fix this: https://github.com/vercel/next.js/issues/55804#issuecomment-1735124191 Ideally it should be test, but I disable for consistency
  NEXT_PUBLIC_APP_ENV: "test"
  DEBUG: "cypress:server:args"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #address of services is the name of the service if both on containers and no port map needed
  DATABASE_URL: "mysql://root:root@mysql-service/terrarossa"
  NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL: ${{vars.NEXTAUTH_URL}}
  AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
  AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
  AUTH0_ISSUER: ${{vars.AUTH0_ISSUER}}
  AUTH0_BASE_URL: ${{vars.AUTH0_BASE_URL}}
  CYPRESS_ADMIN_FORO_MAIL: ${{secrets.CYPRESS_ADMIN_FORO_MAIL}}
  CYPRESS_ADMIN_FORO_PWD: ${{secrets.CYPRESS_ADMIN_FORO_PWD}}
  CYPRESS_ADMIN_ALLENGLAND_MAIL: ${{secrets.CYPRESS_ADMIN_ALLENGLAND_MAIL}}
  CYPRESS_ADMIN_ALLENGLAND_PWD: ${{secrets.CYPRESS_ADMIN_ALLENGLAND_PWD}}
  CYPRESS_USER1_MAIL: ${{secrets.CYPRESS_USER1_MAIL}}
  CYPRESS_USER1_PWD: ${{secrets.CYPRESS_USER1_PWD}}
  CYPRESS_USER2_MAIL: ${{secrets.CYPRESS_USER2_MAIL}}
  CYPRESS_USER2_PWD: ${{secrets.CYPRESS_USER2_PWD}}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  NEXT_PUBLIC_LOGFLARE_API_KEY: ${{ secrets.NEXT_PUBLIC_LOGFLARE_API_KEY }}
  NEXT_PUBLIC_LOGFLARE_SOURCE_ID: ${{ secrets.NEXT_PUBLIC_LOGFLARE_SOURCE_ID }}

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          runTests: false
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: .next

  ui-chrome-tests:
    needs: install
    runs-on: ubuntu-latest
    services:
      mysql-service:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: terrarossa
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    container:
      image: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .next
      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v5
        with:
          # use build step to seed the database, build is already done in install job
          build: npm run db:seed
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          config-file: cypress.config.ts

  ui-chrome-mobile-tests:
    needs: install
    runs-on: ubuntu-latest
    services:
      mysql-service:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: terrarossa
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    container:
      image: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .next
      - name: "UI Tests - Chrome - Mobile"
        uses: cypress-io/github-action@v5
        with:
          config: "viewportWidth=375,viewportHeight=667"
          #use build step to seed the database, build is already done in install job
          build: npm run db:seed
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          browser: chrome
          config-file: cypress.config.ts

  component-testing:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .next
      - name: Run Component Testing
        uses: cypress-io/github-action@v5
        with:
          component: true
          config-file: cypress.config.ts
