name: Vercel - production deployment on push to main (no DB changes)
on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  deploy-code:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    # I want to skip deploy if the committer is Github (already deployed when merged to main)
    steps:
      - name: Check for github committer
        run: |
          echo "github.event.head_commit.committer: ${{ github.event.head_commit.committer.name}}"
          if [ "${{ github.event.head_commit.committer.name}}" == "GitHub" ]; then
            echo "Skipping deploy"
            echo "SKIP_DEPLOY=true" >> $GITHUB_ENV
            exit 0
          fi
      - name: checkout
        if: ${{ !env.SKIP_DEPLOY }}
        uses: actions/checkout@v4
      - name: Install Vercel CLI
        if: ${{ !env.SKIP_DEPLOY }}
        run: npm install --global vercel@latest
      - name: Deploy to Vercel
        if: ${{ !env.SKIP_DEPLOY }}
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
