name: Vercel - preview deployment on push to feature branch
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  deploy-code:
    name: Deploy to Vercel - preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy to Vercel - preview
        run: vercel deploy --token=${{ secrets.VERCEL_TOKEN }}
