name: Vercel - production deployment on push to main (no DB changes)
on:
  push:
    branches: [main]
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  deploy-code:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    # I want to skip deploy if the committer is Github
    steps:
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1
      - name: Check for github committer
        run: |
          if [ "${{ env.GIT_COMMIT_COMMITTER }}" == "GitHub" ]; then
            echo "Skipping deploy"
            exit 0
          fi
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
